### ISSUE TITLE
Unknown min/ unknown max

### ISSUE THREAD

**Issue by karwosts** [m16p/chase-offer-monitor#6]
Was able to get the script working, and it seemed to successfully run through and send the email. 

However every offer says "unknown min" and "unknown max". I am not sure if that is supposed to be working or not.

**Comment by m16p** [comment]
Yeah, that's expected for offers you haven't added yet.  Chase's website doesn't display the minimum or maximum until you add the offer to your card :/

Try adding an offer to a card and rerunning.  (Note that most offers don't have minimums, most only have maximums, so the former could still say unknown).
